 ./stop-qmanager.sh CRC01CRD
 ./stop-qmanager.sh CRC01CMM
 ./stop-qmanager.sh CRC03AGN
 ./stop-qmanager.sh BDV01AGN
 ./stop-qmanager.sh BOD01AGN
 ./stop-qmanager.sh BCRB01AGN
 ./stop-qmanager.sh BBIC01AGN
 ./stop-qmanager.sh BPLS01AGN
 ./stop-qmanager.sh BFC01AGN
 ./stop-qmanager.sh BCRN01AGN
 ./stop-qmanager.sh BPLZ01AGN
 ./stop-qmanager.sh BTES01AGN
 ./stop-qmanager.sh CRC11AGN
 ./stop-qmanager.sh VLVN01AGN
 ./stop-qmanager.sh B100AGN01
 ./stop-qmanager.sh BOD02AGN
 ./stop-qmanager.sh CRC12AGN
 ./stop-qmanager.sh CRC10AGN
 ./stop-qmanager.sh BEXT01AGN
 ./stop-qmanager.sh BMBC01AGN
 ./stop-qmanager.sh CRC14AGN
 ./stop-qmanager.sh CTK01AGN
 ./stop-qmanager.sh BAV01AGN
 ./stop-qmanager.sh BFAN01AGN
 ./stop-qmanager.sh BCRP01AGN
 ./stop-qmanager.sh CPGAGN01
