#!/bin/bash

#echo $COORDINATOR

FTE_CMD="/opt/mqm/bin/"
EXIST=`dspmq | grep $COORDINATOR |  wc -l`
CHANNEL="SYSTEM.ADMIN.SVRCONN"
HOST=`hostname -s`
FTE_CONFIG="/var/mqm/mqft/config/"

if [ "$EXIST" == "0" ]
then 

	crtmqm -c "Coordinator" -q  $COORDINATOR
	strmqm $COORDINATOR
	runmqsc $COORDINATOR << EOF
		DEFINE LISTENER ($COORDINATOR.LST) TRPTYPE (TCP) CONTROL (QMGR) PORT ($COORDINATOR_PORT)
		START LISTENER ($COORDINATOR.LST)
		DEFINE CHANNEL ($CHANNEL) CHLTYPE (SVRCONN)
		START CHANNEL ($CHANNEL)
		DEFINE QLOCAL ($COORDINATOR.DQ) USAGE (NORMAL)
		ALTER QMGR DEADQ($COORDINATOR.DQ)
		ALTER QMGR  CHLAUTH(DISABLED)
                SET CHLAUTH(*)  TYPE(BLOCKUSER) USERLIST(*MQADMIN) ACTION(REMOVE)
		SET CHLAUTH(SYSTEM.*) TYPE(ADDRESSMAP) ADDRESS(*) USERSRC(CHANNEL) ACTION(REPLACE)
                SET CHLAUTH(*)  TYPE(ADDRESSMAP) ADDRESS(*)  USERSRC(CHANNEL) ACTION(ADD)
		ALTER AUTHINFO('SYSTEM.DEFAULT.AUTHINFO.IDPWOS') AUTHTYPE(IDPWOS) CHCKCLNT(NONE)
		ALTER CHANNEL(SYSTEM.ADMIN.SVRCONN) CHLTYPE(SVRCONN) MCAUSER('usrmq')
		ALTER CHANNEL(SYSTEM.DEF.SVRCONN) CHLTYPE(SVRCONN) MCAUSER('usrmq')
		REFRESH SECURITY TYPE(CONNAUTH)
EOF

	echo "Ejejcutamos el comando para definirlo como Coordinator."
	${FTE_CMD}fteSetupCoordination -f -coordinationQMgr $COORDINATOR -coordinationQMgrHost $HOST -coordinationQMgrPort $COORDINATOR_PORT -coordinationQMgrChannel $CHANNEL

	#/var/mqm/mqft/config/CRC01CRD.QM/CRC01CRD.QM.mqsc
	echo "Executind Commands in ${COORDINATOR}.mqsc to create Coordinator "
	runmqsc $COORDINATOR < ${FTE_CONFIG}${COORDINATOR}/${COORDINATOR}.mqsc
else
	echo "El Coordinator $COORDINATOR ya existe."

fi
